//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debtors.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Debtors.Core.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string action_info {
            get {
                return ResourceManager.GetString("action_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addAction {
            get {
                return ResourceManager.GetString("addAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtors.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string callAction {
            get {
                return ResourceManager.GetString("callAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelAction {
            get {
                return ResourceManager.GetString("cancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device does not support phone calls.
        /// </summary>
        internal static string cannotCall {
            get {
                return ResourceManager.GetString("cannotCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device does not support mail messages.
        /// </summary>
        internal static string cannotMail {
            get {
                return ResourceManager.GetString("cannotMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device does not support phone messages.
        /// </summary>
        internal static string cannotSms {
            get {
                return ResourceManager.GetString("cannotSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string currecny {
            get {
                return ResourceManager.GetString("currecny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be deleted. The currency is in use.
        /// </summary>
        internal static string currencyInUse {
            get {
                return ResourceManager.GetString("currencyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt:\u0020.
        /// </summary>
        internal static string debt {
            get {
                return ResourceManager.GetString("debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt is not saved.
        /// </summary>
        internal static string debtIsNotSave {
            get {
                return ResourceManager.GetString("debtIsNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor is not saved.
        /// </summary>
        internal static string debtorIsNotSave {
            get {
                return ResourceManager.GetString("debtorIsNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        internal static string debtsAction {
            get {
                return ResourceManager.GetString("debtsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteAction {
            get {
                return ResourceManager.GetString("deleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string detailsAction {
            get {
                return ResourceManager.GetString("detailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close navigation drawer.
        /// </summary>
        internal static string drawer_close {
            get {
                return ResourceManager.GetString("drawer_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open navigation drawer.
        /// </summary>
        internal static string drawer_open {
            get {
                return ResourceManager.GetString("drawer_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editAction {
            get {
                return ResourceManager.GetString("editAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:\u0020.
        /// </summary>
        internal static string leftToReturn {
            get {
                return ResourceManager.GetString("leftToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mails.
        /// </summary>
        internal static string mails {
            get {
                return ResourceManager.GetString("mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string messageAction {
            get {
                return ResourceManager.GetString("messageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set debtor name.
        /// </summary>
        internal static string noDebtorName {
            get {
                return ResourceManager.GetString("noDebtorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No debts.
        /// </summary>
        internal static string noDebts {
            get {
                return ResourceManager.GetString("noDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers.
        /// </summary>
        internal static string phone_numbers {
            get {
                return ResourceManager.GetString("phone_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete?.
        /// </summary>
        internal static string reallyDelete {
            get {
                return ResourceManager.GetString("reallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to save?.
        /// </summary>
        internal static string reallySave {
            get {
                return ResourceManager.GetString("reallySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set currency.
        /// </summary>
        internal static string setCurrency {
            get {
                return ResourceManager.GetString("setCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set mail address.
        /// </summary>
        internal static string setMailAddress {
            get {
                return ResourceManager.GetString("setMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set phone number.
        /// </summary>
        internal static string setPhoneNumber {
            get {
                return ResourceManager.GetString("setPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set symbol.
        /// </summary>
        internal static string setSymbol {
            get {
                return ResourceManager.GetString("setSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value.
        /// </summary>
        internal static string setValue {
            get {
                return ResourceManager.GetString("setValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string symbol {
            get {
                return ResourceManager.GetString("symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not set.
        /// </summary>
        internal static string valueIsNotSet {
            get {
                return ResourceManager.GetString("valueIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
